[package]
name = "snake_rs"
version = "0.1.0"
authors = ["Caleb Webber <caleb@codingthemsoftly.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.amethyst]
version = "0.15.3"
features = ["vulkan"]
